FROM meshac-client:latest
USER root
RUN sed -i "s#http://archive.ubuntu.com/ubuntu/#http://mirror.us.leaseweb.net/ubuntu/#; s#http://security.ubuntu.com/ubuntu/#http://mirror.us.leaseweb.net/ubuntu/#" /etc/apt/sources.list.d/ubuntu.sources && apt-get update && apt-get install -y --no-install-recommends libegl1 libegl-mesa0 libgles2 libgbm1 libglx-mesa0 libgl1-mesa-dri libsdl2-2.0-0 libwayland-client0 && rm -rf /var/lib/apt/lists/*
USER mc
